In [1]:
from tensorflow.keras.preprocessing.text import one_hot








In [2]:
sent=[
    'the glass of milk',
    'the glass of juice',
    'the cup of tea',
    'i am a good girl',
    'i am a good devoloper'
]

In [3]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'i am a good girl',
 'i am a good devoloper']

In [4]:
voc_size=10000

In [5]:
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[8430, 4757, 6573, 225],
 [8430, 4757, 6573, 6580],
 [8430, 7067, 6573, 7889],
 [9588, 3098, 2702, 6763, 2573],
 [9588, 3098, 2702, 6763, 5159]]

In [6]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [7]:
import numpy as np

In [8]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 8430 4757 6573  225]
 [   0    0    0    0 8430 4757 6573 6580]
 [   0    0    0    0 8430 7067 6573 7889]
 [   0    0    0 9588 3098 2702 6763 2573]
 [   0    0    0 9588 3098 2702 6763 5159]]


In [9]:
dim=10

In [10]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [11]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [13]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 76ms/step


array([[ 0.00734783,  0.01219504,  0.03985213, -0.02627435,  0.01815604,
         0.01384253, -0.02045741, -0.01870304,  0.01151552,  0.01551979],
       [ 0.00734783,  0.01219504,  0.03985213, -0.02627435,  0.01815604,
         0.01384253, -0.02045741, -0.01870304,  0.01151552,  0.01551979],
       [ 0.00734783,  0.01219504,  0.03985213, -0.02627435,  0.01815604,
         0.01384253, -0.02045741, -0.01870304,  0.01151552,  0.01551979],
       [ 0.00734783,  0.01219504,  0.03985213, -0.02627435,  0.01815604,
         0.01384253, -0.02045741, -0.01870304,  0.01151552,  0.01551979],
       [-0.03472076,  0.04603075, -0.00533742,  0.00381603,  0.04618927,
        -0.00844834, -0.02150078, -0.00132412, -0.03706412,  0.00606246],
       [ 0.00928016, -0.04250528,  0.03583295, -0.03383714, -0.03510769,
        -0.03328536, -0.03115731,  0.04076645, -0.00717657, -0.04194207],
       [-0.03077435, -0.04725248, -0.02765222,  0.02064933, -0.03321234,
         0.00218474,  0.04179945, -0.00633433